#!/bin/bash

alias aws:login="aws sso login"
alias docker:login="aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 936143655872.dkr.ecr.us-east-1.amazonaws.com"
alias login:all="aws:login && docker:login"

export AWS_ECR_REGISTRY=936143655872.dkr.ecr.us-east-1.amazonaws.com
export AWS_PROFILE=default
export AWS_CDN_BUCKET="staging.static.payzen.com"

function mono_command() {
        local service_name=$1
        echo "$3 package: $service_name"
        cd ~/Developments/mono/packages/$service_name
        if [[ -f "package.json" ]] then;
		echo "current: $(pwd)"
                $(echo $2)
        else
                for directory in *; do
			mono_command "$service_name/$directory" "$2" "$3"
                done
        fi
        cd - > /dev/null
}

function mono_install() {
	original_folder=$(pwd)
	mono_command "$1" "npm install" "installing"
	cd $original_folder
}

function mono_test() {
	original_folder=$(pwd)
	mono_command "$1" "npm run test" "testing"
	cd $original_folder
}
       
function go_mono() {
	if [[ $2 ]]; then
		cd ~/Developments/mono/packages/$1/$1-$2
	elif [[ $1 ]]; then
		cd ~/Developments/mono/packages/$1
	else
		cd ~/Developments/mono
	fi
}
